### PR TITLE
docToolchain-Version

### PR DESCRIPTION
**Pull request by rdmueller**
this is a manual merge of the current master with my docToolchain version. The merge was not easy and it is likely that I've overseen some changes of the master branch.

What is new?

- folder structure aligned to docToolchain default
- build now contains all docToolchain features
- included a changelog on the first page
- included a stakeholder-diagram with table exportet from Enterprise Architect
- included an example of PowerPoint export for inclusion of slides in documents (SAMM_Ueberblick.pdf)
- included a plantUML sequence example (todo: fully align it to master)
- generates PDFs from all documents. For this, a .gif file had to be converted to .png and table cells with asciidoc content had to be converted to non-asciidoc content - drawbacks of the PDF converter

### CODE REVIEW

**Comment by gernotstarke** [comment]
please allow an hour to check this ...

**Comment by rdmueller** [comment]
...it's not urgent - see my mail

**Comment by gernotstarke** [comment]
I get the following warning:

 The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at exportEA_d3k7l8seegpgdfzpc7d9xcplr.run(/Users/gstarke/projects/venom-example/scripts/exportEA.gradle:4)

**Comment by gernotstarke** [comment]
I get the following errors during "gradle asciidoctor" (will check them in detail later on)

asciidoctor: WARNING: 05-02-ConfiguratorShell.adoc: line 3: section title out of sequence: expected level 1, got level 3
...
asciidoctor: WARNING: 08-02-ViewPipeline.adoc: line 3: section title out of sequence: expected level 1, got level 2
...
asciidoctor: WARNING: arc42-venom.adoc: line 43: include file not found: /Users/gstarke/projects/venom-example/build/docs/changelog.adoc
...
asciidoctor: ERROR: readme.ad: line 7: only book doctypes can contain level 0 sections
...
asciidoctor: ERROR: readme.ad: line 7: only book doctypes can contain level 0 sections
...
asciidoctor: ERROR: readme.ad: line 7: only book doctypes can contain level 0 sections
...
asciidoctor: WARNING: 013-samm-history.adoc: line 3: section title out of sequence: expected level 1, got level 2
...
asciidoctor: WARNING: 031-samm-business-processes.adoc: line 3: section title out of sequence: expected level 1, got level 2
...
asciidoctor: WARNING: 032-samm-aufbauorganisation.adoc: line 3: section title out of sequence: expected level 1, got level 2
...
asciidoctor: ERROR: readme.ad: line 7: only book doctypes can contain level 0 sections

**Comment by gernotstarke** [comment]
gradle (no params, default tasks) runs smoothly :-)

**Comment by gernotstarke** [comment]
checked the generated arc42 pdf/html: ok

**Comment by gernotstarke** [comment]
samm-ueberblick.* seems to be broken.
index-orga.html seems ok, pdf version has wrong heading, tables are weird (pdf export issue?)

will merge now :-)

**Comment by rdmueller** [comment]
ok. it seems that you didn't use the wrapper, did you?
I'll check all your findings hopefully later today...

**Pull request merged**
